package com.example.thirdtydayofwellness.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF6c538c)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFeedcff)
val md_theme_light_onPrimaryContainer = Color(0xFF260d44)
val md_theme_light_secondary = Color(0xFF645a6f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFebddf7)
val md_theme_light_onSecondaryContainer = Color(0xFF20182a)
val md_theme_light_tertiary = Color(0xFF80525a)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFffd9de)
val md_theme_light_onTertiaryContainer = Color(0xFF321018)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFfff7ff)
val md_theme_light_onSurface = Color(0xFF1d1a20)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DD)
val md_theme_light_onSurfaceVariant = Color(0xFF4a454e)
val md_theme_light_outline = Color(0xFF7b757f)
val md_theme_light_inverseOnSurface = Color(0xFFf6eef6)
val md_theme_light_inverseSurface = Color(0xFF332f35)
val md_theme_light_inversePrimary = Color(0xFFd7bafb)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006C4C)
val md_theme_light_outlineVariant = Color(0xFFccc4cf)
val md_theme_light_scrim = Color(0xFF000000)